ARG RUNTIME_IMAGE
ARG BUILD_IMAGE

FROM $BUILD_IMAGE AS builder  

WORKDIR /app

COPY package*.json ./

RUN yarn

COPY . .

ARG CLIENT_URL
ARG JIRA_BASE_URL
ARG JIRA_API_TOKEN
ARG JIRA_USERNAME
ARG JIRA_PROJECT_KEY_ONE
ARG JIRA_PROJECT_KEY_TWO
ARG JIRA_PROJECT_KEY_THREE
ARG JIRA_PROJECT_KEY_FOUR
ARG P_GATEWAY_URL
ARG OPENAI_ASSISTANT_ID
ARG OPENAI_API_KEY
ARG P_TOKEN

ENV CLIENT_URL=$CLIENT_URL
ENV JIRA_BASE_URL=$JIRA_BASE_URL
ENV JIRA_API_TOKEN=$JIRA_API_TOKEN
ENV JIRA_USERNAME=$JIRA_USERNAME
ENV JIRA_PROJECT_KEY_ONE=$JIRA_PROJECT_KEY_ONE
ENV JIRA_PROJECT_KEY_TWO=$JIRA_PROJECT_KEY_TWO
ENV JIRA_PROJECT_KEY_THREE=$JIRA_PROJECT_KEY_THREE
ENV JIRA_PROJECT_KEY_FOUR=$JIRA_PROJECT_KEY_FOUR
ENV P_GATEWAY_URL=$P_GATEWAY_URL
ENV OPENAI_ASSISTANT_ID=$OPENAI_ASSISTANT_ID
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV P_TOKEN=$P_TOKEN

RUN yarn build

FROM $RUNTIME_IMAGE AS runner

WORKDIR /app

COPY --from=builder /app .

ARG CLIENT_URL
ARG JIRA_BASE_URL
ARG JIRA_API_TOKEN
ARG JIRA_USERNAME
ARG JIRA_PROJECT_KEY_ONE
ARG JIRA_PROJECT_KEY_TWO
ARG JIRA_PROJECT_KEY_THREE
ARG JIRA_PROJECT_KEY_FOUR
ARG P_GATEWAY_URL
ARG OPENAI_ASSISTANT_ID
ARG OPENAI_API_KEY
ARG P_TOKEN

ENV CLIENT_URL=$CLIENT_URL
ENV JIRA_BASE_URL=$JIRA_BASE_URL
ENV JIRA_API_TOKEN=$JIRA_API_TOKEN
ENV JIRA_USERNAME=$JIRA_USERNAME
ENV JIRA_PROJECT_KEY_ONE=$JIRA_PROJECT_KEY_ONE
ENV JIRA_PROJECT_KEY_TWO=$JIRA_PROJECT_KEY_TWO
ENV JIRA_PROJECT_KEY_THREE=$JIRA_PROJECT_KEY_THREE
ENV JIRA_PROJECT_KEY_FOUR=$JIRA_PROJECT_KEY_FOUR
ENV P_GATEWAY_URL=$P_GATEWAY_URL
ENV OPENAI_ASSISTANT_ID=$OPENAI_ASSISTANT_ID
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV P_TOKEN=$P_TOKEN

EXPOSE 5000

CMD [ "yarn", "start" ]